hubei:
  wuhan:
    name: mwt

druid:
  servlet:
    urlMappings: /druid/*
    allow:
    deny: 192.168.2.110
    loginUsername:
    loginPassword:
    resetEnable:

server:
  port: 8080
#spring.profiles.active=dev

#spring.application.name=eureka-server1

#spring.application.name=hello-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

  instance:
    prefer-ip-address: true
#eureka.server.enable-self-preservation=false

#eureka.client.serviceUrl.defaultZone=http://localhost:8888/eureka,http://localhost:7777/eureka


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mwt
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      #配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 3
      max-active: 10

      #配置获取连接等待超时的时间
      max-wait: 10000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      #如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

      #配置监控统计拦截的filters
      filters: stat


mybatis:
  mapper-locations: classpath:mapping/*.xml


